### ISSUE TITLE
I like it, favorite mod 

### ISSUE THREAD

**Issue by ghost** [FunkyShoeMan/TheWildsExtended#1]

**Comment by FunkyShoeMan** [comment]
thank you jammer man

**Comment by FunkyShoeMan** [comment]
man this just messed my contact in the readme.md

**Comment by ghost** [comment]
> 

nvm the mod is kinda poo poo bc it has no content but i get that things take time.

**Comment by FunkyShoeMan** [comment]
Jammer Moment.
